name: Check for Chainguard Images
description: Check if the image used in Dockerfile is a Chainguard image
runs:
  using: composite
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'
    
    - name: Run check_images script
      run: python ${{ github.action_path }}/check_images.py
      env:
        CHAINGUARD_FILE: ${{ github.action_path }}/chainguard.json
      shell: bash
